// SPDX-FileCopyrightText: 2024 Cesanta Software Limited
// SPDX-License-Identifier: GPL-2.0-only or commercial
// Generated by Mongoose Wizard, https://mongoose.ws/wizard/

// Default mock implementation of the API callbacks

#include "mongoose_glue.h"
static uint64_t s_action_timeout_reboot;  // Time when reboot ends
bool glue_check_reboot(void) {
  return s_action_timeout_reboot > mg_now(); // Return true if reboot is in progress
}
void glue_start_reboot(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_reboot = mg_now() + 1000; // Start reboot, finish after 1 second
}

static uint64_t s_action_timeout_reformat;  // Time when reformat ends
bool glue_check_reformat(void) {
  return s_action_timeout_reformat > mg_now(); // Return true if reformat is in progress
}
void glue_start_reformat(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_reformat = mg_now() + 1000; // Start reformat, finish after 1 second
}

static uint64_t s_action_timeout_save_event;  // Time when save_event ends
bool glue_check_save_event(void) {
  return s_action_timeout_save_event > mg_now(); // Return true if save_event is in progress
}
void glue_start_save_event(struct mg_str params) {
  MG_DEBUG(("Passed parameters: [%.*s]", params.len, params.buf));
  s_action_timeout_save_event = mg_now() + 1000; // Start save_event, finish after 1 second
}

static struct state s_state = {42, 27, 67, 10, "1.0.0", true, false, 83};
void glue_get_state(struct state *data) {
  *data = s_state;  // Sync with your device
}

static struct relais s_relais = {false, true, false};
void glue_get_relais(struct relais *data) {
  *data = s_relais;  // Sync with your device
}
void glue_set_relais(struct relais *data) {
  s_relais = *data; // Sync with your device
}

static struct network_settings s_network_settings = {"192.168.1.221", "192.168.1.1", "255.255.255.0", true};
void glue_get_network_settings(struct network_settings *data) {
  *data = s_network_settings;  // Sync with your device
}
void glue_set_network_settings(struct network_settings *data) {
  s_network_settings = *data; // Sync with your device
}

static struct settings s_settings = {"edit & save me", 2, 123.12345, 17, true};
void glue_get_settings(struct settings *data) {
  *data = s_settings;  // Sync with your device
}
void glue_set_settings(struct settings *data) {
  s_settings = *data; // Sync with your device
}

static struct security s_security = {"admin", "user"};
void glue_get_security(struct security *data) {
  *data = s_security;  // Sync with your device
}
void glue_set_security(struct security *data) {
  s_security = *data; // Sync with your device
}

static struct events s_events[] = {
  {0, 1738653279, 2, 2, "Some event"},
  {0, 1738653279, 2, 2, "Some event"},
  {0, 1738653279, 2, 2, "Some event"},
};
bool glue_get_events(struct events *data, size_t i) {
  size_t array_size = sizeof(s_events) / sizeof(s_events[0]);
  if (i >= array_size) return false;
  *data = s_events[i];  // Sync with your device
  return true;
}
void glue_set_events(struct events *data, size_t i) {
  size_t array_size = sizeof(s_events) / sizeof(s_events[0]);
  if (i < array_size) s_events[i] = *data; // Sync with your device
}

